"""The verbatim multi-tier disclaimer — a DETERMINISTIC CONSTANT (build-plan fix C / invariant 11 /
DC-08). The wrapper injects this exact text so it can never be paraphrased by an LLM node. V-FIN-01
asserts an exact match. The graph's N-DISCLAIMER only chooses the bracket-specific *additions*.
"""
from __future__ import annotations

BASE_DISCLAIMER = """\
⚠️ IMPORTANT DISCLAIMER

This report is generated by epiphany-finance, an AI-powered tool, and is provided for
informational and educational purposes ONLY. It does NOT constitute professional financial,
investment, legal, or tax advice.

- This is artificial intelligence. Errors, outdated information, and misinterpretations are
  possible. All figures, rates, and recommendations should be independently verified.
- Do not make financial decisions based solely on this report.
- Before taking any action, consult a qualified financial advisor, certified financial planner
  (CFP), accountant (CPA), or attorney licensed in your jurisdiction.
- Past performance of any investment does not guarantee future results.
- This tool does not have access to your bank accounts or real-time financial data unless you
  have provided it directly. The analysis is only as accurate as the information you supplied.
- Investment prices shown are sourced from Yahoo Finance and may be delayed; see the Data
  Freshness section for the exact timestamp and age of every quote.

⚠️ END DISCLAIMER"""

# bracket -> mandatory additional clause (appended, never replacing the base)
BRACKET_ADDITIONS = {
    "destitute": "Emergency resources are listed for reference — contact local social services, "
                 "211 (US), or a shelter network for immediate assistance.",
    "homeless": "Emergency resources are listed for reference — contact local social services, "
                "211 (US), or a shelter network for immediate assistance.",
    "ultra-hnw": "Tax optimization strategies described are for legal tax reduction only. This tool "
                 "does not advise on tax evasion, which is illegal. Consult a licensed CPA or tax "
                 "attorney.",
}


# Mandatory addition for benefit-dependent users (SSI/SSDI/Medicaid/SNAP) — names the RIGHT
# authorities (SSA / benefits counselor), which the generic CFP/CPA list does not. Appended, never
# replacing the base. Keyed on the benefit_dependent flag, not the bracket.
BENEFIT_ADDITION = (
    "Benefit rules (SSI, SSDI, Medicaid, SNAP) vary by state and year and carry income and asset "
    "limits — saving or earning more can REDUCE or END benefits. Before changing your income, "
    "savings, or assets, verify with the Social Security Administration (SSA), your state Medicaid/"
    "benefits office, or a benefits counselor, and ask about an ABLE account.")


def disclaimer_for(bracket: str | None, benefit_dependent: bool = False) -> str:
    """Base disclaimer + any bracket-specific addition + the benefit-safety addition when the user
    depends on means-tested benefits (verbatim). BASE_DISCLAIMER stays an exact substring so the
    top+bottom verbatim check still holds."""
    out = BASE_DISCLAIMER
    add = BRACKET_ADDITIONS.get((bracket or "").strip().lower())
    if add:
        out += f"\n\n*{add}*"
    if benefit_dependent:
        out += f"\n\n*{BENEFIT_ADDITION}*"
    return out
